# Generated by Django 5.2.2 on 2025-06-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadjets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
