# Generated by Django 5.2.2 on 2025-06-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='link_youtube',
            field=models.URLField(null=True, verbose_name='вставте ссылку'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Напишите название книги'),
        ),
    ]
