# Generated by Django 5.2.2 on 2025-06-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_link_youtube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='напишите отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
