# Generated by Django 5.2.2 on 2025-06-12 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_newsbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не меньше 1.'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не больше 5.')])),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценка',
            },
        ),
        migrations.AlterModelOptions(
            name='newsbook',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автор'},
        ),
    ]
