# Generated by Django 5.2.2 on 2025-06-12 14:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_alter_newsbook_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='choice_book',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не меньше 1.'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не больше 5.')], verbose_name='Оценка от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(verbose_name='Напишите отзыв'),
        ),
    ]
