# Generated by Django 5.2.2 on 2025-06-16 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Обложка книги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type_book', models.CharField(choices=[('Magic realism', 'Magic realism'), ('Novel', 'Novel'), ('Fantasy', 'Fantasy')], max_length=20, verbose_name='Тип книги')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('card_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('not_confirmed', 'Не подтвержден')], default='not_confirmed', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.book', verbose_name='Книга')),
            ],
        ),
    ]
