# Generated by Django 5.2.2 on 2025-06-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('card_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('not_confirmed', 'Не подтвержден')], default='not_confirmed', max_length=20)),
            ],
        ),
    ]
